name: CI

# Controls when the action will run.
on:
  pull_request:

# Global environment variables
env:
  CI: true

# Jobs
jobs:
  # Set up tests
  set_up:
    name: Set up
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
  # Lint job
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [set_up]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
      - name: Cache Next.js build and lint output
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}1-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}1-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - run: yarn install
      # Lint files
      - name: Lint files
        run: yarn lint
